# Generated by Django 3.0.8 on 2020-07-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('grade', models.CharField(max_length=5)),
                ('min_quantity', models.IntegerField()),
                ('is_in_stock', models.BooleanField()),
            ],
        ),
    ]
