# Generated by Django 3.0.8 on 2020-07-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_produce_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
